name: app_check_test
description: A new Flutter project.

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_app_check: ^0.2.0
  firebase_auth: ^4.10.0
  firebase_core: ^2.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  rexios_lints: ^5.0.0

dependency_overrides:
  firebase_core_web:
    git:
      url: https://github.com/Rexios80/flutterfire
      ref: b1b359f793f56de70707a119f1d0914509b3d1c9
      path: packages/firebase_core/firebase_core_web
  firebase_app_check_web:
    git:
      url: https://github.com/Rexios80/flutterfire
      ref: b1b359f793f56de70707a119f1d0914509b3d1c9
      path: packages/firebase_app_check/firebase_app_check_web

flutter:
  uses-material-design: true
